### ISSUE TITLE
Apps have different title after launching, and still show as favourite

### ISSUE THREAD

**Issue by fawtytoo** [dsboger/gnome-shell-extension-super-tab-launcher#5] opened 2018-04-08 23:18 UTC
Some apps, such as VirtualBox, have a different title (and icon depending on icon theme), after launching and still show at the end of the app list as a non-running favourite app.

**Comment by dsboger** [comment] 2018-04-08 23:54
That's strange. I cannot reproduce it, so I'll need some more info. Which distro are you using and how were these apps installed (e.g. package manager, flatpak, snap, manually, etc.)? Does the app icon also show twice in the GNOME Shell's favorites (dash)? Lastly, can you post the output of `$ gsettings get org.gnome.shell favorite-apps`.

Something like that happens to me when I install an update while the app is running. It seems that somehow GNOME Shell "detects" that desktop file was updated and the app entry is duplicated. But that is fixed once I close the app and reopen it.

Thanks for reporting!

**Comment by phenest** [comment] 2018-04-09 08:16
A bit more testing reveals that if you launch from a favourite, and then restart the shell via Alt-F2 r, then the title of that app changes (and the icon in the case of VirtualBox), and the favourite is showing again. Not all favourites exhibit the issue. I installed VirtualBox manually from their web site.

I was doing some work to my own extension, so I was restarting the shell frequently. In normal use, it doesn't seem to be a problem.

The same thing happens with the Dash.

**Comment by dsboger** [comment] 2018-04-09 12:10
If the same behavior is also visible in the Dash, that means it is probably an issue with the way the Shell handles running apps. I think there is nothing I can do in the extension. Can you please report this issue to the Shell developers (https://gitlab.gnome.org/GNOME/gnome-shell/issues) and then post the issue link here so that I can follow? Thanks again.

**Closed as completed** 2018-10-29 14:26 UTC
